name: Build and Test

on:
  push:
    branches: [ next, master ]
  pull_request:
    branches: [ next, master ]


jobs:
  # Build the library and site
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        cmd: yarn install && yarn build

  # Run the test suite
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: cypress-io/github-action@v1
        with:
          build: yarn build
          runTests: false # just build site
      - uses: cypress-io/github-action@v1
        with:
          install: false
          working-directory: tests
          start: yarn serve
          wait-on: http://localhost:1234
